"""Safe Markdown rendering for the published longform viewer."""

import html
import re
from typing import Any
from urllib.parse import unquote, urlsplit
from xml.etree import ElementTree

import bleach  # type: ignore[import-untyped]  # Package has no py.typed marker.
import markdown  # type: ignore[import-untyped]  # Package has no py.typed marker.
from markdown.extensions import Extension  # type: ignore[import-untyped]
from markdown.extensions.fenced_code import (  # type: ignore[import-untyped]
    FencedBlockPreprocessor,
)
from markdown.inlinepatterns import InlineProcessor  # type: ignore[import-untyped]
from markdown.postprocessors import Postprocessor  # type: ignore[import-untyped]
from markdown.util import HTML_PLACEHOLDER  # type: ignore[import-untyped]

_ALLOWED_TAGS = frozenset(
    {
        "a",
        "blockquote",
        "br",
        "code",
        "del",
        "em",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "hr",
        "li",
        "ol",
        "p",
        "pre",
        "strong",
        "table",
        "tbody",
        "td",
        "th",
        "thead",
        "tr",
        "ul",
    }
)
_ALLOWED_PROTOCOLS = frozenset({"http", "https", "mailto"})
_CODE_CLASS_PATTERN = re.compile(r"^language-[A-Za-z0-9_+-]{1,50}$")
_WIKILINK_PATTERN = r"\[\[([^]|]+?)(?:\|([^]]+?))?\]\]"


class _TrackedFencedBlockPreprocessor(FencedBlockPreprocessor):
    """Track only HTML generated by the fenced-code extension itself."""

    def __init__(
        self,
        md: markdown.Markdown,
        config: dict[str, Any],
        generated_indices: set[int],
    ) -> None:
        super().__init__(md, config)
        self._generated_indices = generated_indices

    def run(self, lines: list[str]) -> list[str]:
        """Record the stash entries created from fenced Markdown code blocks."""
        first_index = self.md.htmlStash.html_counter
        processed = super().run(lines)
        self._generated_indices.update(
            range(first_index, self.md.htmlStash.html_counter)
        )
        return processed


class _SafeHtmlPostprocessor(Postprocessor):
    """Restore extension-generated code HTML and discard author raw HTML."""

    def __init__(self, md: markdown.Markdown, generated_indices: set[int]) -> None:
        super().__init__(md)
        self._generated_indices = generated_indices

    def run(self, text: str) -> str:
        """Resolve Markdown stash placeholders without parsing author HTML."""
        placeholder = HTML_PLACEHOLDER % r"([0-9]+)"
        pattern = re.compile(f"<p>{placeholder}</p>|{placeholder}")

        def replace(match: re.Match[str]) -> str:
            key = int(match.group(1) or match.group(2))
            if key not in self._generated_indices:
                return ""
            return str(self.md.htmlStash.rawHtmlBlocks[key])

        return pattern.sub(replace, text)


class _WikiLinkInlineProcessor(InlineProcessor):
    """Create wiki-link elements without injecting an HTML source string."""

    def handleMatch(
        self, match: re.Match[str], data: str
    ) -> tuple[ElementTree.Element | None, int | None, int | None]:
        """Convert one ``[[target|label]]`` expression to an anchor element."""
        target = match.group(1).strip()
        label = (match.group(2) or match.group(1)).strip()
        if not target:
            return None, None, None

        element = ElementTree.Element("a")
        element.set("class", "wikilink")
        element.set("data-target", target)
        element.text = label
        return element, match.start(0), match.end(0)


class _SafeLongformExtension(Extension):
    """Install safe raw-HTML handling and native wiki-link parsing."""

    def extendMarkdown(self, md: markdown.Markdown) -> None:
        """Register the longform-specific Markdown processors."""
        generated_indices: set[int] = set()
        md.preprocessors.deregister("fenced_code_block")
        md.preprocessors.register(
            _TrackedFencedBlockPreprocessor(
                md,
                {"lang_prefix": "language-"},
                generated_indices,
            ),
            "fenced_code_block",
            25,
        )
        md.inlinePatterns.register(
            _WikiLinkInlineProcessor(_WIKILINK_PATTERN, md),
            "kraken_wikilink",
            175,
        )
        # ``extra`` enables attr_list, which would let authors forge the
        # class/data-target pair reserved for server-generated wiki links.
        md.treeprocessors.deregister("attr_list")
        md.postprocessors.deregister("raw_html")
        md.postprocessors.register(
            _SafeHtmlPostprocessor(md, generated_indices),
            "raw_html",
            30,
        )


def _decode_url_for_validation(value: str) -> str:
    """Decode entity and percent encodings used to disguise a URL scheme."""
    decoded = value
    for _ in range(3):
        updated = unquote(html.unescape(decoded))
        if updated == decoded:
            break
        decoded = updated
    return decoded


def _is_safe_url(value: str) -> bool:
    """Return whether a rendered link target is safe for browser navigation."""
    decoded = _decode_url_for_validation(value)
    if not decoded or "\\" in decoded:
        return False
    if any(character.isspace() or ord(character) < 0x20 for character in decoded):
        return False
    if decoded.startswith("#"):
        return len(decoded) > 1
    if decoded.startswith("//"):
        return False

    try:
        parsed = urlsplit(decoded)
        _ = parsed.port
    except ValueError:
        return False

    scheme = parsed.scheme.lower()
    if scheme not in _ALLOWED_PROTOCOLS:
        return False
    if parsed.username is not None or parsed.password is not None:
        return False
    if scheme in {"http", "https"}:
        return bool(parsed.hostname)
    return scheme == "mailto" and not parsed.netloc and bool(parsed.path)


def _allow_attribute(tag: str, name: str, value: str) -> bool:
    """Apply the longform allowlist to one element attribute."""
    if tag == "a":
        if name == "href":
            return _is_safe_url(value)
        if name == "title":
            return True
        if name == "class":
            return value == "wikilink"
        if name == "data-target":
            return True
        return False
    if tag == "code" and name == "class":
        return _CODE_CLASS_PATTERN.fullmatch(value) is not None
    return False


_CLEANER = bleach.Cleaner(
    tags=_ALLOWED_TAGS,
    attributes=_allow_attribute,
    protocols=_ALLOWED_PROTOCOLS,
    strip=True,
    strip_comments=True,
)


def render_longform_markdown(source: str) -> str:
    """Render stored Markdown to the viewer's strictly sanitized HTML subset."""
    rendered = markdown.markdown(
        source,
        extensions=["extra", "nl2br", _SafeLongformExtension()],
        output_format="html",
    )
    return _CLEANER.clean(rendered)
