"""Summary Widget Module.

Provides a widget for displaying and managing AI-generated item summaries.
"""

from datetime import datetime

from PySide6.QtCore import Signal, Slot
from PySide6.QtWidgets import (
    QApplication,
    QFrame,
    QHBoxLayout,
    QLabel,
    QMessageBox,
    QVBoxLayout,
    QWidget,
)

from src.core.summary_data import SummaryData
from src.core.theme_manager import ThemeManager
from src.gui.widgets.standard_buttons import (
    DestructiveButton,
    PrimaryButton,
    StandardButton,
)
from src.gui.widgets.wiki_text_edit import WikiTextEdit


class SummaryWidget(QWidget):
    """Widget to display and manage item summaries.

    Features:
    - Markdown display via WikiTextEdit
    - Metadata footer (Timestamp, Model)
    - Stale content warning
    - Generate/update controls
    """

    generate_requested = Signal()
    edit_committed = Signal(str)
    delete_requested = Signal()

    def __init__(self, parent: QWidget | None = None) -> None:
        """Initialize the summary widget.

        Args:
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self._summary_data: SummaryData | None = None
        self._pre_edit_text = ""
        self._controls_enabled = True
        self._setup_ui()
        self._apply_styles()
        ThemeManager().theme_changed.connect(self._apply_styles)

    def _setup_ui(self) -> None:
        """Set up the user interface components."""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        # Stale Banner
        self.stale_banner = QFrame()
        self.stale_banner.setObjectName("stale_banner")
        stale_layout = QHBoxLayout(self.stale_banner)
        stale_layout.setContentsMargins(8, 4, 8, 4)

        # Use a warning icon/color if possible, for now just text
        self.stale_label = QLabel(
            "⚠️ Content has changed since this summary was generated."
        )
        stale_layout.addWidget(self.stale_label)

        self.stale_banner.hide()
        layout.addWidget(self.stale_banner)

        # Text Display
        self.text_display = WikiTextEdit()
        self.text_display.setReadOnly(True)
        self.text_display.setMinimumHeight(100)  # Ensure visible space
        layout.addWidget(self.text_display)

        # Footer
        footer_layout = QHBoxLayout()

        self.metadata_label = QLabel()
        self.metadata_label.setObjectName("metadata")
        footer_layout.addWidget(self.metadata_label)

        footer_layout.addStretch()

        self.cancel_btn = StandardButton("Cancel")
        self.cancel_btn.clicked.connect(self._cancel_edit)
        self.cancel_btn.hide()
        footer_layout.addWidget(self.cancel_btn)

        self.done_btn = PrimaryButton("Done")
        self.done_btn.clicked.connect(self._commit_edit)
        self.done_btn.hide()
        footer_layout.addWidget(self.done_btn)

        self.delete_btn = DestructiveButton("Delete")
        self.delete_btn.clicked.connect(self._confirm_delete)
        footer_layout.addWidget(self.delete_btn)

        self.edit_btn = StandardButton("Edit")
        self.edit_btn.clicked.connect(self._begin_edit)
        footer_layout.addWidget(self.edit_btn)

        self.copy_btn = StandardButton("Copy")
        self.copy_btn.clicked.connect(self._copy_to_clipboard)
        footer_layout.addWidget(self.copy_btn)

        self.generate_btn = PrimaryButton("Generate")
        self.generate_btn.clicked.connect(self.generate_requested.emit)
        footer_layout.addWidget(self.generate_btn)

        layout.addLayout(footer_layout)
        self.clear_summary()

    def set_summary(self, data: SummaryData) -> None:
        """Updates the widget with summary data."""
        self._summary_data = data
        self._leave_edit_mode()
        self.text_display.set_wiki_text(data.text)

        # Format timestamp
        if data.timestamp:
            dt = datetime.fromtimestamp(data.timestamp).strftime("%Y-%m-%d %H:%M")
        else:
            dt = "Unknown"

        if data.origin == "manual":
            self.metadata_label.setText(f"Manual summary · edited {dt}")
        else:
            model = data.model or "Unknown"
            self.metadata_label.setText(f"Generated by {model} on {dt}")

        self.set_stale(False)
        self.generate_btn.setText("Regenerate")
        self._update_action_visibility(True)

    def set_stale(self, stale: bool) -> None:
        """Displays or hides the stale warning."""
        self.stale_banner.setVisible(stale)
        if stale:
            self.generate_btn.setText("Update Summary")

    def clear_summary(self) -> None:
        """Reset the widget to its empty state."""
        self._summary_data = None
        self._leave_edit_mode()
        self.text_display.clear()
        self.metadata_label.clear()
        self.stale_banner.hide()
        self.generate_btn.setText("Generate")
        self._update_action_visibility(False)

    def set_controls_enabled(self, enabled: bool) -> None:
        """Enable or disable all summary mutation controls."""
        self._controls_enabled = enabled
        if not enabled and not self.text_display.isReadOnly():
            self._cancel_edit()
        has_summary = self._summary_data is not None
        self.generate_btn.setEnabled(enabled)
        self.edit_btn.setEnabled(enabled and has_summary)
        self.delete_btn.setEnabled(enabled and has_summary)
        self.done_btn.setEnabled(enabled)
        self.cancel_btn.setEnabled(enabled)
        self.text_display.setReadOnly(True)

    def _begin_edit(self) -> None:
        """Enter inline summary-editing mode."""
        if not self._summary_data or not self._controls_enabled:
            return
        self._pre_edit_text = self.text_display.get_wiki_text()
        self.text_display.setReadOnly(False)
        self.text_display.setFocus()
        self._set_edit_mode(True)

    def _commit_edit(self) -> None:
        """Leave edit mode and emit the staged manual summary text."""
        text = self.text_display.get_wiki_text().strip()
        if not text:
            QMessageBox.warning(
                self,
                "Empty Summary",
                "A summary cannot be empty. Use Delete to remove it.",
            )
            return
        self._leave_edit_mode()
        self.edit_committed.emit(text)

    def _cancel_edit(self) -> None:
        """Discard the current inline edit."""
        self.text_display.set_wiki_text(self._pre_edit_text)
        self._leave_edit_mode()

    def _confirm_delete(self) -> None:
        """Confirm and emit a staged summary deletion."""
        if not self._summary_data or not self._controls_enabled:
            return
        confirm = QMessageBox.question(
            self,
            "Delete Summary",
            "Delete this summary? The removal is applied when you save the item.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No,
        )
        if confirm != QMessageBox.StandardButton.Yes:
            return
        self.clear_summary()
        self.delete_requested.emit()

    def _set_edit_mode(self, editing: bool) -> None:
        """Update action visibility for inline editing."""
        self.edit_btn.setVisible(not editing)
        self.delete_btn.setVisible(not editing)
        self.copy_btn.setVisible(not editing)
        self.generate_btn.setVisible(not editing)
        self.done_btn.setVisible(editing)
        self.cancel_btn.setVisible(editing)

    def _leave_edit_mode(self) -> None:
        """Return to the read-only summary display."""
        self.text_display.setReadOnly(True)
        self._set_edit_mode(False)

    def _update_action_visibility(self, has_summary: bool) -> None:
        """Show actions that are valid for the current summary state."""
        self.edit_btn.setVisible(has_summary)
        self.delete_btn.setVisible(has_summary)
        self.copy_btn.setVisible(has_summary)

    def _copy_to_clipboard(self) -> None:
        """Copies summary text to clipboard."""
        QApplication.clipboard().setText(self.text_display.toPlainText())

    @Slot(dict)
    def _apply_styles(self, _theme: dict | None = None) -> None:
        """Apply stale-state and metadata colours from the active theme."""
        theme = ThemeManager().get_theme()
        self.stale_label.setStyleSheet(
            f"color: {theme['error']}; font-weight: bold;"
        )
        self.metadata_label.setStyleSheet(
            f"color: {theme['text_dim']}; font-size: 10px;"
        )
        self.stale_banner.setStyleSheet(
            f"""
            QFrame#stale_banner {{
                background-color: {theme['surface']};
                border: 1px solid {theme['error']};
                border-radius: 4px;
            }}
        """
        )
