"""Summary Widget Module.

Provides a widget for displaying and managing AI-generated item summaries.
"""
from datetime import datetime

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QApplication,
    QFrame,
    QHBoxLayout,
    QLabel,
    QVBoxLayout,
    QWidget,
)

from src.core.summary_data import SummaryData
from src.gui.widgets.standard_buttons import PrimaryButton, StandardButton
from src.gui.widgets.wiki_text_edit import WikiTextEdit


class SummaryWidget(QWidget):
    """Widget to display and manage item summaries.

    Features:
    - Markdown display via WikiTextEdit
    - Metadata footer (Timestamp, Model)
    - Stale content warning
    - Generate/update controls
    """

    generate_requested = Signal()

    def __init__(self, parent: QWidget | None = None) -> None:
        """Initialize the summary widget.
        
        Args:
            parent: Optional parent widget.
        """
        super().__init__(parent)
        self._setup_ui()
        self._apply_styles()

    def _setup_ui(self) -> None:
        """Set up the user interface components."""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        # Stale Banner
        self.stale_banner = QFrame()
        self.stale_banner.setObjectName("stale_banner")
        stale_layout = QHBoxLayout(self.stale_banner)
        stale_layout.setContentsMargins(8, 4, 8, 4)

        # Use a warning icon/color if possible, for now just text
        stale_label = QLabel("⚠️ Content has changed since this summary was generated.")
        stale_label.setStyleSheet("color: #FF6B6B; font-weight: bold;")
        stale_layout.addWidget(stale_label)

        self.stale_banner.hide()
        layout.addWidget(self.stale_banner)

        # Text Display
        self.text_display = WikiTextEdit()
        self.text_display.setReadOnly(True)
        self.text_display.setMinimumHeight(100)  # Ensure visible space
        layout.addWidget(self.text_display)

        # Footer
        footer_layout = QHBoxLayout()

        self.metadata_label = QLabel()
        self.metadata_label.setObjectName("metadata")
        self.metadata_label.setStyleSheet("color: #888888; font-size: 10px;")
        footer_layout.addWidget(self.metadata_label)

        footer_layout.addStretch()

        self.copy_btn = StandardButton("Copy")
        self.copy_btn.clicked.connect(self._copy_to_clipboard)
        footer_layout.addWidget(self.copy_btn)

        self.generate_btn = PrimaryButton("Generate")
        self.generate_btn.clicked.connect(self.generate_requested.emit)
        footer_layout.addWidget(self.generate_btn)

        layout.addLayout(footer_layout)

    def set_summary(self, data: SummaryData) -> None:
        """Updates the widget with summary data."""
        self.text_display.set_wiki_text(data.text)

        # Format timestamp
        if data.timestamp:
            dt = datetime.fromtimestamp(data.timestamp).strftime("%Y-%m-%d %H:%M")
        else:
            dt = "Unknown"

        model = data.model or "Unknown"
        self.metadata_label.setText(f"Generated by {model} on {dt}")

        # Reset stale state implicitly on update?
        # Usually logic outside controls this, but if we set new data, it's fresh.
        # But let the caller handle explicit stale flags since data might be old but newly loaded.
        # However, update button text.
        self.generate_btn.setText("Regenerate")

    def set_stale(self, stale: bool) -> None:
        """Displays or hides the stale warning."""
        self.stale_banner.setVisible(stale)
        if stale:
            self.generate_btn.setText("Update Summary")

    def _copy_to_clipboard(self) -> None:
        """Copies summary text to clipboard."""
        QApplication.clipboard().setText(self.text_display.toPlainText())

    def _apply_styles(self) -> None:
        """Apply custom styling."""
        # Banner style
        self.stale_banner.setStyleSheet(
            """
            QFrame#stale_banner {
                background-color: rgba(255, 107, 107, 0.1);
                border: 1px solid rgba(255, 107, 107, 0.3);
                border-radius: 4px;
            }
        """
        )
