"""Shared constants owned by the GUI layer.

Keeping widget configuration here lets both the application facade and GUI
components use the same values without making ``src.gui`` depend on
``src.app``.
"""

from src.core.map_constants import (
    DEFAULT_MARKER_ICONS_PATH,
    MAP_LAYER_BASEMAP_NODE_ID,
    MAP_LAYER_DEFAULT_GROUP_NAME,
    MAP_LAYER_DEFAULT_OPACITY,
    MAP_LAYER_TYPE_BASEMAP,
    MAP_LAYER_TYPE_GROUP,
    MAP_LAYER_TYPE_MARKER,
    MAP_LAYER_TYPE_PATH,
    MAP_LAYER_TYPE_RASTER,
    MAP_LAYER_TYPE_REGION,
    MAP_LAYER_TYPE_SNAPSHOT,
    MAP_LAYER_Z_BASE,
    MAP_LAYER_Z_FOOTPRINTS,
    MAP_LAYER_Z_MAP_BG,
    MAP_LAYER_Z_MARKERS,
    MAP_LAYER_Z_RASTER,
    MAP_LAYER_Z_SPACING,
    MAP_LAYER_Z_TRAJECTORIES,
    MAP_LAYER_Z_UI_OVERLAY,
    MAP_ROLE_DETAIL,
    MAP_ROLE_MASTER,
)
from src.core.settings import WINDOW_SETTINGS_APP, WINDOW_SETTINGS_KEY
from src.core.version import VERSION

__all__ = [
    "DEFAULT_MARKER_ICONS_PATH",
    "MAP_LAYER_BASEMAP_NODE_ID",
    "MAP_LAYER_DEFAULT_GROUP_NAME",
    "MAP_LAYER_DEFAULT_OPACITY",
    "MAP_LAYER_TYPE_BASEMAP",
    "MAP_LAYER_TYPE_GROUP",
    "MAP_LAYER_TYPE_MARKER",
    "MAP_LAYER_TYPE_PATH",
    "MAP_LAYER_TYPE_RASTER",
    "MAP_LAYER_TYPE_REGION",
    "MAP_LAYER_TYPE_SNAPSHOT",
    "MAP_LAYER_Z_BASE",
    "MAP_LAYER_Z_FOOTPRINTS",
    "MAP_LAYER_Z_MAP_BG",
    "MAP_LAYER_Z_MARKERS",
    "MAP_LAYER_Z_RASTER",
    "MAP_LAYER_Z_SPACING",
    "MAP_LAYER_Z_TRAJECTORIES",
    "MAP_LAYER_Z_UI_OVERLAY",
    "MAP_ROLE_DETAIL",
    "MAP_ROLE_MASTER",
    "VERSION",
    "WINDOW_SETTINGS_APP",
    "WINDOW_SETTINGS_KEY",
]

# World and file-dialog settings.
SETTINGS_ACTIVE_DB_KEY = "active_world"
SUPPORTED_IMAGE_FORMATS = ["png", "jpg", "jpeg", "bmp", "webp"]
IMAGE_FILE_FILTER = (
    f"Images ({' '.join([f'*.{ext}' for ext in SUPPORTED_IMAGE_FORMATS])})"
)

# Editor behavior and layout.
AUTOSAVE_DELAY_MS = 2_000
WIKI_EDITOR_MAX_LINE_LENGTH = 90
SEMANTIC_COMPLETION_MIN_PREFIX_LEN = 3
TOOLTIP_DELAY_MS = 1_500
TOOLTIP_DURATION_MS = 5_000
SHEET_VALUE_MAX_LINES = 4
EDITOR_FORM_VERTICAL_SPACING = 12
EDITOR_SECTION_SPACING = 4
EDITOR_LIST_SPACING = 2
EDITOR_DETAILS_MIN_HEIGHT = 400
EDITOR_RELATION_LIST_MIN_HEIGHT = 80
EDITOR_ICON_BUTTON_SIZE = 32
RELATION_PICKER_MIN_WIDTH = 250
RELATION_PICKER_MAX_WIDTH = 400
RELATION_PICKER_MIN_HEIGHT = 80
RELATION_PICKER_MAX_HEIGHT = 120

# Temporal visualization.
TEMPORAL_FUTURE_OPACITY = 0.7
MAP_TEMPORAL_GHOST_OPACITY = 0.2
TEMPORAL_FUTURE_SATURATION_FACTOR = 0.8
TEMPORAL_FUTURE_LIGHTNESS_BOOST = 0.1

# Default visual style for paths and regions.
MAP_FEATURE_DEFAULT_STROKE_COLOR = "#3498DB"
MAP_FEATURE_DEFAULT_STROKE_WIDTH = 2.0
MAP_FEATURE_DEFAULT_FILL_COLOR = "#403498DB"
MAP_FEATURE_DEFAULT_DASH_PATTERN: list[float] = []
MAP_FEATURE_REGION_STROKE_COLOR = "#2C3E50"
MAP_FEATURE_REGION_FILL_COLOR = "#303498DB"
MAP_FEATURE_SELECTION_PEN_COLOR = "#FFFFFF"
MAP_FEATURE_SELECTION_PEN_WIDTH = 2.0
MAP_FEATURE_HIT_AREA_MARGIN = 6
MAP_FEATURE_MIN_HIT_AREA_WIDTH = 10
MAP_FEATURE_LABEL_FONT_FAMILY = "Segoe UI"
MAP_FEATURE_LABEL_FONT_SIZE = 9
MAP_FEATURE_LABEL_COLOR = "#333333"
MAP_FEATURE_Z_VALUE = 8
MAP_FEATURE_HOVER_DEBOUNCE_MS = 100
MAP_FEATURE_CLICK_THRESHOLD_PX = 5

# Vertex editing and snapping.
MAP_VERTEX_HANDLE_RADIUS = 5
MAP_VERTEX_HANDLE_COLOR = "#e74c3c"
MAP_VERTEX_HANDLE_BORDER_COLOR = "#FFFFFF"
MAP_MIDPOINT_HANDLE_RADIUS = 4
MAP_MIDPOINT_HANDLE_COLOR = "#2ecc71"
MAP_MIDPOINT_HANDLE_BORDER_COLOR = "#FFFFFF"
MAP_MIDPOINT_GHOST_OPACITY = 0.4
MAP_MIDPOINT_HOVER_OPACITY = 0.9
MAP_EDIT_DASH_PATTERN = [6, 3]
MAP_EDIT_STROKE_COLOR = "#e67e22"
MAP_EDIT_STROKE_WIDTH = 5.0
MAP_SNAP_RADIUS_PX = 10.0
MAP_SNAP_INDICATOR_VERTEX_COLOR = "#f1c40f"
MAP_SNAP_INDICATOR_EDGE_COLOR = "#3498db"
MAP_SNAP_INDICATOR_RADIUS = 6
MAP_SNAP_INDICATOR_BORDER_COLOR = "#FFFFFF"
MAP_SNAP_INDICATOR_BORDER_WIDTH = 1.5
MAP_ZOOM_IN_FACTOR = 1.25

# Analysis table severity colors.
ANALYSIS_SEVERITY_CRITICAL_COLOR = "#e74c3c"
ANALYSIS_SEVERITY_WARNING_COLOR = "#e67e22"
ANALYSIS_SEVERITY_INFO_COLOR = "#3498db"
