"""Application Constants.

Stores default values for UI configuration and magic numbers.
"""

from src.core.map_constants import (
    DEFAULT_MARKER_ICONS_PATH,
    MAP_DEFAULT_WIDTH_METERS,
    MAP_LAYER_BASEMAP_NODE_ID,
    MAP_LAYER_DEFAULT_GROUP_NAME,
    MAP_LAYER_DEFAULT_MAX_ZOOM,
    MAP_LAYER_DEFAULT_MIN_ZOOM,
    MAP_LAYER_DEFAULT_OPACITY,
    MAP_LAYER_TYPE_BASEMAP,
    MAP_LAYER_TYPE_GROUP,
    MAP_LAYER_TYPE_MARKER,
    MAP_LAYER_TYPE_PATH,
    MAP_LAYER_TYPE_RASTER,
    MAP_LAYER_TYPE_REGION,
    MAP_LAYER_TYPE_SNAPSHOT,
    MAP_LAYER_Z_BASE,
    MAP_LAYER_Z_FEATURES,
    MAP_LAYER_Z_FOOTPRINTS,
    MAP_LAYER_Z_MAP_BG,
    MAP_LAYER_Z_MARKERS,
    MAP_LAYER_Z_RASTER,
    MAP_LAYER_Z_SPACING,
    MAP_LAYER_Z_TRAJECTORIES,
    MAP_LAYER_Z_UI_OVERLAY,
    MAP_NESTING_DEPTH_CAP,
    MAP_ROLE_DETAIL,
    MAP_ROLE_MASTER,
    TEMPORAL_SNAPSHOT_CACHE_MAX,
)
from src.core.semantic_config import (
    SEMANTIC_COMPLETION_ENABLE_EMBEDDING,
    SEMANTIC_COMPLETION_PROBE_ON_WINDOWS,
    SEMANTIC_COMPLETION_PROBE_TIMEOUT_S,
)
from src.core.settings import (
    WINDOW_SETTINGS_APP,
    WINDOW_SETTINGS_KEY,
)
from src.core.version import VERSION
from src.gui.constants import (
    ANALYSIS_SEVERITY_CRITICAL_COLOR,
    ANALYSIS_SEVERITY_INFO_COLOR,
    ANALYSIS_SEVERITY_WARNING_COLOR,
    AUTOSAVE_DELAY_MS,
    EDITOR_DETAILS_MIN_HEIGHT,
    EDITOR_FORM_VERTICAL_SPACING,
    EDITOR_ICON_BUTTON_SIZE,
    EDITOR_LIST_SPACING,
    EDITOR_RELATION_LIST_MIN_HEIGHT,
    EDITOR_SECTION_SPACING,
    IMAGE_FILE_FILTER,
    MAP_EDIT_DASH_PATTERN,
    MAP_EDIT_STROKE_COLOR,
    MAP_EDIT_STROKE_WIDTH,
    MAP_FEATURE_CLICK_THRESHOLD_PX,
    MAP_FEATURE_DEFAULT_DASH_PATTERN,
    MAP_FEATURE_DEFAULT_FILL_COLOR,
    MAP_FEATURE_DEFAULT_STROKE_COLOR,
    MAP_FEATURE_DEFAULT_STROKE_WIDTH,
    MAP_FEATURE_HIT_AREA_MARGIN,
    MAP_FEATURE_HOVER_DEBOUNCE_MS,
    MAP_FEATURE_LABEL_COLOR,
    MAP_FEATURE_LABEL_FONT_FAMILY,
    MAP_FEATURE_LABEL_FONT_SIZE,
    MAP_FEATURE_MIN_HIT_AREA_WIDTH,
    MAP_FEATURE_REGION_FILL_COLOR,
    MAP_FEATURE_REGION_STROKE_COLOR,
    MAP_FEATURE_SELECTION_PEN_COLOR,
    MAP_FEATURE_SELECTION_PEN_WIDTH,
    MAP_FEATURE_Z_VALUE,
    MAP_MIDPOINT_GHOST_OPACITY,
    MAP_MIDPOINT_HANDLE_BORDER_COLOR,
    MAP_MIDPOINT_HANDLE_COLOR,
    MAP_MIDPOINT_HANDLE_RADIUS,
    MAP_MIDPOINT_HOVER_OPACITY,
    MAP_SNAP_INDICATOR_BORDER_COLOR,
    MAP_SNAP_INDICATOR_BORDER_WIDTH,
    MAP_SNAP_INDICATOR_EDGE_COLOR,
    MAP_SNAP_INDICATOR_RADIUS,
    MAP_SNAP_INDICATOR_VERTEX_COLOR,
    MAP_SNAP_RADIUS_PX,
    MAP_TEMPORAL_GHOST_OPACITY,
    MAP_VERTEX_HANDLE_BORDER_COLOR,
    MAP_VERTEX_HANDLE_COLOR,
    MAP_VERTEX_HANDLE_RADIUS,
    MAP_ZOOM_IN_FACTOR,
    RELATION_PICKER_MAX_HEIGHT,
    RELATION_PICKER_MAX_WIDTH,
    RELATION_PICKER_MIN_HEIGHT,
    RELATION_PICKER_MIN_WIDTH,
    SEMANTIC_COMPLETION_MIN_PREFIX_LEN,
    SETTINGS_ACTIVE_DB_KEY,
    SHEET_VALUE_MAX_LINES,
    SUPPORTED_IMAGE_FORMATS,
    TEMPORAL_FUTURE_LIGHTNESS_BOOST,
    TEMPORAL_FUTURE_OPACITY,
    TEMPORAL_FUTURE_SATURATION_FACTOR,
    TOOLTIP_DELAY_MS,
    TOOLTIP_DURATION_MS,
    WIKI_EDITOR_MAX_LINE_LENGTH,
)

__all__ = [
    "ANALYSIS_SEVERITY_CRITICAL_COLOR",
    "ANALYSIS_SEVERITY_INFO_COLOR",
    "ANALYSIS_SEVERITY_WARNING_COLOR",
    "AUTOSAVE_DELAY_MS",
    "DEFAULT_MARKER_ICONS_PATH",
    "EDITOR_DETAILS_MIN_HEIGHT",
    "EDITOR_FORM_VERTICAL_SPACING",
    "EDITOR_ICON_BUTTON_SIZE",
    "EDITOR_LIST_SPACING",
    "EDITOR_RELATION_LIST_MIN_HEIGHT",
    "EDITOR_SECTION_SPACING",
    "IMAGE_FILE_FILTER",
    "MAP_EDIT_DASH_PATTERN",
    "MAP_EDIT_STROKE_COLOR",
    "MAP_EDIT_STROKE_WIDTH",
    "MAP_DEFAULT_WIDTH_METERS",
    "MAP_FEATURE_CLICK_THRESHOLD_PX",
    "MAP_FEATURE_DEFAULT_DASH_PATTERN",
    "MAP_FEATURE_DEFAULT_FILL_COLOR",
    "MAP_FEATURE_DEFAULT_STROKE_COLOR",
    "MAP_FEATURE_DEFAULT_STROKE_WIDTH",
    "MAP_FEATURE_HIT_AREA_MARGIN",
    "MAP_FEATURE_HOVER_DEBOUNCE_MS",
    "MAP_FEATURE_LABEL_COLOR",
    "MAP_FEATURE_LABEL_FONT_FAMILY",
    "MAP_FEATURE_LABEL_FONT_SIZE",
    "MAP_FEATURE_MIN_HIT_AREA_WIDTH",
    "MAP_FEATURE_REGION_FILL_COLOR",
    "MAP_FEATURE_REGION_STROKE_COLOR",
    "MAP_FEATURE_SELECTION_PEN_COLOR",
    "MAP_FEATURE_SELECTION_PEN_WIDTH",
    "MAP_FEATURE_Z_VALUE",
    "MAP_LAYER_BASEMAP_NODE_ID",
    "MAP_LAYER_DEFAULT_GROUP_NAME",
    "MAP_LAYER_DEFAULT_MAX_ZOOM",
    "MAP_LAYER_DEFAULT_MIN_ZOOM",
    "MAP_LAYER_DEFAULT_OPACITY",
    "MAP_LAYER_TYPE_BASEMAP",
    "MAP_LAYER_TYPE_GROUP",
    "MAP_LAYER_TYPE_MARKER",
    "MAP_LAYER_TYPE_PATH",
    "MAP_LAYER_TYPE_RASTER",
    "MAP_LAYER_TYPE_REGION",
    "MAP_LAYER_TYPE_SNAPSHOT",
    "MAP_LAYER_Z_BASE",
    "MAP_LAYER_Z_FEATURES",
    "MAP_LAYER_Z_FOOTPRINTS",
    "MAP_LAYER_Z_MAP_BG",
    "MAP_LAYER_Z_MARKERS",
    "MAP_LAYER_Z_RASTER",
    "MAP_LAYER_Z_SPACING",
    "MAP_LAYER_Z_TRAJECTORIES",
    "MAP_LAYER_Z_UI_OVERLAY",
    "MAP_NESTING_DEPTH_CAP",
    "MAP_MIDPOINT_GHOST_OPACITY",
    "MAP_MIDPOINT_HANDLE_BORDER_COLOR",
    "MAP_MIDPOINT_HANDLE_COLOR",
    "MAP_MIDPOINT_HANDLE_RADIUS",
    "MAP_MIDPOINT_HOVER_OPACITY",
    "MAP_ROLE_DETAIL",
    "MAP_ROLE_MASTER",
    "MAP_SNAP_INDICATOR_BORDER_COLOR",
    "MAP_SNAP_INDICATOR_BORDER_WIDTH",
    "MAP_SNAP_INDICATOR_EDGE_COLOR",
    "MAP_SNAP_INDICATOR_RADIUS",
    "MAP_SNAP_INDICATOR_VERTEX_COLOR",
    "MAP_SNAP_RADIUS_PX",
    "MAP_TEMPORAL_GHOST_OPACITY",
    "MAP_VERTEX_HANDLE_BORDER_COLOR",
    "MAP_VERTEX_HANDLE_COLOR",
    "MAP_VERTEX_HANDLE_RADIUS",
    "MAP_ZOOM_IN_FACTOR",
    "RELATION_PICKER_MAX_HEIGHT",
    "RELATION_PICKER_MAX_WIDTH",
    "RELATION_PICKER_MIN_HEIGHT",
    "RELATION_PICKER_MIN_WIDTH",
    "SEMANTIC_COMPLETION_ENABLE_EMBEDDING",
    "SEMANTIC_COMPLETION_MIN_PREFIX_LEN",
    "SEMANTIC_COMPLETION_PROBE_ON_WINDOWS",
    "SEMANTIC_COMPLETION_PROBE_TIMEOUT_S",
    "SETTINGS_ACTIVE_DB_KEY",
    "SHEET_VALUE_MAX_LINES",
    "SUPPORTED_IMAGE_FORMATS",
    "TEMPORAL_SNAPSHOT_CACHE_MAX",
    "TEMPORAL_FUTURE_LIGHTNESS_BOOST",
    "TEMPORAL_FUTURE_OPACITY",
    "TEMPORAL_FUTURE_SATURATION_FACTOR",
    "TOOLTIP_DELAY_MS",
    "TOOLTIP_DURATION_MS",
    "VERSION",
    "WIKI_EDITOR_MAX_LINE_LENGTH",
    "WINDOW_SETTINGS_APP",
    "WINDOW_SETTINGS_KEY",
]


# Background semantic-search thread shutdown grace period.
AI_SEARCH_THREAD_SHUTDOWN_MS = 10_000
WINDOW_TITLE = f"Project Kraken - v{VERSION} (Beta)"
DEFAULT_WINDOW_WIDTH = 1280
DEFAULT_WINDOW_HEIGHT = 720
DEFAULT_WORLD_NAME = "Default World"
SETTINGS_LAYOUTS_KEY = "saved_layouts"
SETTINGS_WORKSPACE_LAYOUT_KEY = "workspace_layout"
SETTINGS_LAST_ITEM_ID_KEY = "last_selected_item_id"
SETTINGS_LAST_ITEM_TYPE_KEY = "last_selected_item_type"
SETTINGS_AUTO_RELATION_KEY = "wiki/auto_create_relations"
SETTINGS_FILTER_CONFIG_KEY = "tag_filter_config"
SETTINGS_RASTER_BRUSH_PRESETS_KEY = "raster/brush_presets"
SETTINGS_CONTEXT_TAGS_PREFIX = "worlds/{world_id}/context_tags/v1"

# Status Messages
STATUS_DB_INIT_FAIL = "Database Initialization Failed!"
STATUS_ERROR_PREFIX = "Error: "


# Default marker icons bundled with the application

# File Dialog Filters
# Semantic Completion Constants
SEMANTIC_COMPLETION_MIN_SCORE = 0.85  # Minimum cosine similarity to surface a suggestion
SEMANTIC_COMPLETION_TOP_K = 5  # Max candidates fetched from the semantic index
SEMANTIC_COMPLETION_DEBOUNCE_MS = 350  # Keystroke debounce before querying the worker

# UI Timing Constants
# Delays for deferred initialization and UI updates
UI_INIT_DELAY_MS = 100  # Initial delay for completing app initialization
UI_SEARCH_INDEX_REFRESH_DELAY_MS = 100  # Delay for search index status refresh
UI_CLEANUP_DELAY_MS = 200  # Delay for cleanup operations

# Provider Retry Configuration
PROVIDER_RETRY_WAIT_TIME_S = 1.0  # Wait time between provider retries

# Unified List Constants
UNIFIED_LIST_MIN_WIDTH = 250
UNIFIED_LIST_MIN_HEIGHT = 200
UNIFIED_LIST_PREFERRED_WIDTH = 350
UNIFIED_LIST_PREFERRED_HEIGHT = 500
UNIFIED_LIST_MESSAGE_TIMEOUT_MS = 3000
UNIFIED_LIST_DELETE_CONFIRM_TIMEOUT_MS = 1000

# Navigation Constants
NAVIGATION_SELECTION_DELAY_MS = (
    250  # Delay to allow drag operations to cancel selection
)
