"""Domain constants for map layers and portable map state."""

MAP_LAYER_DEFAULT_OPACITY = 1.0
MAP_LAYER_DEFAULT_MIN_ZOOM = 0.0
MAP_LAYER_DEFAULT_MAX_ZOOM = float("inf")

MAP_LAYER_TYPE_GROUP = "group"
MAP_LAYER_TYPE_MARKER = "marker"
MAP_LAYER_TYPE_SNAPSHOT = "raster_snapshot"
MAP_LAYER_TYPE_PATH = "path"
MAP_LAYER_TYPE_REGION = "region"
MAP_LAYER_TYPE_RASTER = "raster"
MAP_LAYER_TYPE_BASEMAP = "basemap"

MAP_ROLE_MASTER = "master"
MAP_ROLE_DETAIL = "detail"
MAP_NESTING_DEPTH_CAP = 5

MAP_LAYER_BASEMAP_NODE_ID = "__basemap__"
MAP_LAYER_DEFAULT_GROUP_NAME = "Default"

MAP_LAYER_Z_MAP_BG = 0.0
MAP_LAYER_Z_TRAJECTORIES = 0.5
MAP_LAYER_Z_RASTER = 4.0
MAP_LAYER_Z_FEATURES = 8.0
MAP_LAYER_Z_FOOTPRINTS = 9.0
MAP_LAYER_Z_MARKERS = 10.0
MAP_LAYER_Z_UI_OVERLAY = 100.0
MAP_LAYER_Z_SPACING = 0.01
MAP_LAYER_Z_BASE = 20.0

TEMPORAL_SNAPSHOT_CACHE_MAX = 20

# Compatibility only. Zero means the map has no physical calibration.
MAP_DEFAULT_WIDTH_METERS = 0.0
DEFAULT_MARKER_ICONS_PATH = "default_assets/icons/markers"
