"""Install staged Ruff hooks and a Git pre-push gate bound to this Python."""

from __future__ import annotations

import shlex
import subprocess
import sys
from pathlib import Path

from scripts.preflight import ROOT, git_output

MARKER = "# ProjektKraken pre-push quality gate"


def install_push_hook() -> Path:
    """Install the complete-ref gate without replacing an unrelated hook."""
    hook = Path(git_output("rev-parse", "--git-path", "hooks/pre-push"))
    if not hook.is_absolute():
        hook = ROOT / hook
    if hook.with_name("pre-push.legacy").exists():
        raise RuntimeError(
            "A legacy push hook exists; preserve and integrate it before "
            "installing Kraken's gate."
        )
    if hook.exists():
        existing = hook.read_text(encoding="utf-8")
        known = MARKER in existing or (
            "# File generated by pre-commit" in existing
            and "--hook-type=pre-push" in existing
        )
        if not known:
            raise RuntimeError(
                f"Existing push hook at {hook}; preserve and integrate it before "
                "installing Kraken's gate."
            )
    python = shlex.quote(Path(sys.executable).as_posix())
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(
        f"#!/bin/sh\n{MARKER}\nexec {python} -m scripts.preflight push --pre-push\n",
        encoding="utf-8",
        newline="\n",
    )
    hook.chmod(0o755)
    return hook


def main() -> int:
    """Install both hook types from the developer's selected environment."""
    try:
        hook = install_push_hook()
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "pre_commit",
                "install",
                "--hook-type",
                "pre-commit",
            ],
            cwd=ROOT,
            check=False,
        )
    except (OSError, RuntimeError) as error:
        print(f"Cannot install hooks: {error}", file=sys.stderr)
        return 1
    if result.returncode:
        return result.returncode
    print(f"Installed Kraken push gate: {hook}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
