import time
from unittest.mock import patch

import pytest
from PySide6.QtWidgets import QApplication, QMessageBox

from src.core.summary_data import SummaryData
from src.gui.widgets.summary_widget import SummaryWidget


@pytest.fixture
def summary_widget(qtbot):
    widget = SummaryWidget()
    qtbot.addWidget(widget)
    widget.show()
    return widget


def test_initial_state_is_empty(summary_widget):
    assert summary_widget.text_display.toPlainText() == ""
    assert summary_widget.generate_btn.isEnabled()


def test_set_summary_updates_display(summary_widget):
    data = SummaryData(
        text="## Summary\nContent", hash="123", timestamp=time.time(), model="gpt-4"
    )
    summary_widget.set_summary(data)

    assert "Content" in summary_widget.text_display.toPlainText()
    assert "gpt-4" in summary_widget.metadata_label.text()


def test_set_summary_rerenders_same_text_after_document_is_cleared(summary_widget):
    data = SummaryData(
        text="Summary remains visible",
        hash="123",
        timestamp=time.time(),
        model="gpt-4",
    )
    summary_widget.set_summary(data)
    summary_widget.clear_summary()

    summary_widget.set_summary(data)

    assert summary_widget.text_display.toPlainText() == "Summary remains visible"


def test_set_stale_shows_warning(summary_widget):
    summary_widget.set_stale(True)
    assert summary_widget.stale_banner.isVisible()

    summary_widget.set_stale(False)
    assert not summary_widget.stale_banner.isVisible()


def test_generate_signal_emitted(summary_widget, qtbot):
    with qtbot.waitSignal(summary_widget.generate_requested, timeout=1000) as blocker:
        summary_widget.generate_btn.click()
    assert blocker.signal_triggered


def test_copy_button_copies_text(summary_widget, qtbot):
    data = SummaryData(
        text="Copy this", hash="123", timestamp=time.time(), model="gpt-4"
    )
    summary_widget.set_summary(data)

    # Mock clipboard or check functionality if possible.
    # For unit test without full GUI env, we might just check slot connection
    # or use QClipboard if available.
    clipboard = QApplication.clipboard()
    clipboard.clear()

    summary_widget.copy_btn.click()

    assert clipboard.text() == "Copy this"


def test_manual_summary_metadata_drops_ai_attribution(summary_widget):
    data = SummaryData(
        text="Edited by the user",
        hash="123",
        timestamp=time.time(),
        model="",
        origin="manual",
    )

    summary_widget.set_summary(data)

    assert "Manual summary" in summary_widget.metadata_label.text()
    assert "Generated by" not in summary_widget.metadata_label.text()


def test_inline_edit_can_be_cancelled(summary_widget):
    data = SummaryData(
        text="Original text",
        hash="123",
        timestamp=time.time(),
        model="model",
    )
    summary_widget.set_summary(data)

    summary_widget.edit_btn.click()
    summary_widget.text_display.set_wiki_text("Changed text")
    summary_widget.cancel_btn.click()

    assert summary_widget.text_display.get_wiki_text() == "Original text"
    assert summary_widget.text_display.isReadOnly()


def test_inline_edit_emits_committed_text(summary_widget, qtbot):
    data = SummaryData(
        text="Original text",
        hash="123",
        timestamp=time.time(),
        model="model",
    )
    summary_widget.set_summary(data)

    summary_widget.edit_btn.click()
    summary_widget.text_display.set_wiki_text("Manual replacement")
    with qtbot.waitSignal(summary_widget.edit_committed, timeout=1000) as blocker:
        summary_widget.done_btn.click()

    assert blocker.args == ["Manual replacement"]
    assert summary_widget.text_display.isReadOnly()


def test_delete_requires_confirmation_and_emits_request(summary_widget, qtbot):
    data = SummaryData(
        text="Delete me",
        hash="123",
        timestamp=time.time(),
        model="model",
    )
    summary_widget.set_summary(data)

    with patch(
        "src.gui.widgets.summary_widget.QMessageBox.question",
        return_value=QMessageBox.StandardButton.Yes,
    ):
        with qtbot.waitSignal(summary_widget.delete_requested, timeout=1000):
            summary_widget.delete_btn.click()

    assert summary_widget.text_display.toPlainText() == ""
    assert summary_widget.generate_btn.text() == "Generate"


def test_disabling_controls_exits_edit_mode(summary_widget):
    data = SummaryData(
        text="Original text",
        hash="123",
        timestamp=time.time(),
        model="model",
    )
    summary_widget.set_summary(data)
    summary_widget.edit_btn.click()

    summary_widget.set_controls_enabled(False)

    assert summary_widget.text_display.isReadOnly()
    assert not summary_widget.generate_btn.isEnabled()
    assert not summary_widget.edit_btn.isEnabled()
    assert not summary_widget.delete_btn.isEnabled()


def test_legacy_summary_defaults_to_ai_origin():
    data = SummaryData.from_dict(
        {
            "text": "Legacy",
            "hash": "123",
            "timestamp": 1.0,
            "model": "old-model",
        }
    )

    assert data.origin == "ai"
